import { C, GS } from './constants.js';

export const state = {
    gs: GS.MENU,
    paused: false,
    lt: performance.now(),
    et: 0,
    gt: 0,
    sc: 0,
    bestSc: 0,
    totalBl: 0,
    totalSuccess: 0,
    blocks: [],
    parts: [],
    stars: [],
    pl: {
        y: C.H / 2,
        vy: 0,
        grav: 'DOWN',
        sx: 1,
        sy: 1,
        sq: 0,
        trail: [],
        tt: 0,
        lastGY: 0,
        lastSide: null,
        onSurface: false,
        char: 'FOX',
    },
    curSong: null,
    tapTimes: [],
    tapStart: 0,
    tapTimer: 0,
    detectedBPM: 0,
    scoreA: { on: false, s: 0, t: 0 },
    flash: 0,
    flashW: 0,
    flashPos: { x: 0, y: 0 },
    countT: 0,
    guideFlash: 0,
    curHue: 200,
    energyMult: 1.0,
    smoothEnergy: 0,
    lastBeatEnergy: 0,
    beatCooldown: 0,
    beatFlash: 0,
    dynamicGap: C.GAP,
    volume: 1.0,
    volDisplayT: 0,
    lastTier: 0,
    tierMsg: { text: '', sub: '', t: 0, tier: 0 },
    opponent: null,
    roomCode: null,
    isOnline: false,
    netTimer: 0,
};
